name: HACS Validation

on:
  push:
    branches:
      - main 
  pull_request:
    branches:
      - main 
  release:
    types: [published]

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: HACS validation
        uses: hacs/action@main # Use the latest stable version
        with:
          category: frontend 